service:
  # Host to bind the service on
  host: 0.0.0.0
  # HTTP port
  http_port: 6333
  # Disable gRPC completely
  grpc_port: null
  # Maximum size of POST data in a single request in megabytes
  max_request_size_mb: 32
  # Enable CORS headers in REST API
  enable_cors: true
  # Enable web dashboard
  enable_dashboard: true

storage:
  # Where to store all the data
  storage_path: ./storage
  # Where to store snapshots
  snapshots_path: ./snapshots
  # Store payloads on disk to save RAM
  on_disk_payload: true
  
  # Performance tuning
  performance:
    # Number of parallel threads used for search operations. If 0 - auto selection
    max_search_threads: 0
    # Max number of threads for optimization. If 0 - auto selection
    max_optimization_threads: 0

  # HNSW index configuration
  hnsw_index:
    # Number of edges per node in the index graph
    m: 16
    # Number of neighbours to consider during index building
    ef_construct: 100
    # Minimal size of vectors for additional indexing
    full_scan_threshold_kb: 10000

# Disable telemetry
telemetry_disabled: true
